import { useEffect, useState } from "react";
import { Alert, Linking, PermissionsAndroid, Platform, View } from "react-native";
import { useOffline } from "../../app/providers/OfflineProvider";
import { Body, Button, Field, Heading, Label, LinkRow, Panel, Toggle, ui } from "../../components/OfflineUI";
import { offlineProtection, type AppRule, type InstalledApp } from "../../native/OfflineProtection";

export function PermissionsScreen() {
  const { snapshot: data, command, run } = useOffline(); if (!data) return null;
  return <View style={ui.stack}><Heading title="Protection setup" subtitle="Only enable the access you need. You stay in control of your device." /><Panel><Body strong>App restriction access</Body><Body>Restrainify uses Android Accessibility to see the foreground app and visible interface identifiers, recognize selected feeds, and show a restriction screen. Tapping “Back to home” returns you Home.</Body><Body>No screenshots, typed text, or screen contents are saved or uploaded. Without this access, app limits and feed restrictions cannot be enforced. You can revoke access in Android Settings.</Body><Toggle title="I agree to this use of Accessibility" value={data.settings.accessibilityConsent} onChange={value => void command("setting", { key: "accessibilityConsent", value })} /><Button title={data.capabilities.accessibility ? "Review Accessibility access" : "Open Accessibility settings"} disabled={!data.settings.accessibilityConsent} onPress={() => void run(() => offlineProtection.settings("accessibility"))} /></Panel><Panel><Body strong>Usage Access</Body><Body>Reads per-app foreground time to show usage and enforce the limits you choose. Without access, screen-time data and limits are unavailable.</Body><Button title={data.capabilities.usage ? "Review Usage Access" : "Enable Usage Access"} onPress={() => void run(() => offlineProtection.settings("usage"))} /></Panel><Panel><Body strong>Service notifications</Body><Body>The local VPN has an ongoing notification while running. Allow notifications to keep its status visible.</Body><Button title="Allow notifications" tone="secondary" onPress={() => void run(async () => { if (Platform.OS === "android" && Number(Platform.Version) >= 33) { const result = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS); if (result !== "granted") throw new Error("Notifications remain disabled. You can enable them in Android Settings."); } })} /></Panel><Panel><Body strong>Battery settings</Body><Body>Some phones stop background services. If protection repeatedly disconnects, review the battery settings for Restrainify. An exception cannot guarantee service survival.</Body><Button title="Review battery settings" tone="secondary" onPress={() => void run(() => offlineProtection.settings("battery"))} /></Panel></View>;
}

export function WebsiteScreen() {
  const { snapshot: data, command, run } = useOffline();
  const [domain, setDomain] = useState(""); const [allow, setAllow] = useState(false);
  if (!data) return null;
  const save = async () => { if (await command("domain", { domain, allow, enabled: true })) setDomain(""); };
  return <View style={ui.stack}><Heading title="A quieter web" subtitle="DNS protection with rules you control." /><Panel><Toggle title="Website protection" value={data.settings.websiteEnabled} onChange={value => void command("setting", { key: "websiteEnabled", value })} /><View style={ui.wrap}>{(["vpn", "private"] as const).map(mode => <Button key={mode} title={mode === "vpn" ? "Local DNS VPN" : "Private DNS"} tone={data.settings.dnsMode === mode ? "primary" : "secondary"} onPress={() => void command("setting", { key: "dnsMode", value: mode })} />)}</View><Body>{data.settings.dnsMode === "vpn" ? "The local VPN routes DNS requests only. Cloudflare Families resolves domains and filters its maintained adult/malware categories; your custom blocklist is checked on this device. Allowed exceptions use Cloudflare's standard resolver." : "Private DNS encrypts DNS requests to the provider configured in Android. Set the provider hostname to family.cloudflare-dns.com in Android → Private DNS."}</Body><Body>DNS protection cannot reliably block apps using their own encrypted DNS, cached addresses, or direct IP connections. It does not inspect HTTPS content or guarantee SafeSearch.</Body>{data.settings.dnsMode === "vpn" ? <><Body strong>{data.capabilities.vpn ? "Local VPN connected" : "Local VPN disconnected"}</Body>{data.capabilities.vpnError && <Body>{data.capabilities.vpnError}</Body>}<Body>Starting this replaces another active VPN. Normal app traffic stays on its usual connection. DNS requests reveal domain names to the resolver; no full URLs or page contents are sent.</Body><Button title={data.capabilities.vpn ? "Disconnect VPN" : "Agree & connect DNS VPN"} disabled={!data.settings.websiteEnabled} onPress={() => void run(data.capabilities.vpn ? offlineProtection.stopVpn : offlineProtection.startVpn)} /></> : <><Body strong>Configured hostname: {data.capabilities.privateDns || "None detected"}</Body><Body>Custom domain exceptions apply only to the local VPN. A configured hostname is not proof the provider is filtering successfully.</Body><Button title="Open Android network settings" onPress={() => void run(() => offlineProtection.settings("dns"))} /></>}<Button title="Cloudflare Families privacy & setup" tone="secondary" onPress={() => void run(() => Linking.openURL("https://developers.cloudflare.com/1.1.1.1/setup/#1111-for-families"))} /></Panel>
    <Label>YOUR DOMAIN RULES · {data.settings.domains.length}</Label><Panel><Field label="Domain" placeholder="example.com" value={domain} onChange={setDomain} /><Toggle title="Allow this domain instead" detail="An allow rule takes precedence for this domain and its subdomains." value={allow} onChange={setAllow} /><Button title={allow ? "Add exception" : "Block domain"} disabled={!domain.trim()} onPress={() => void save()} /></Panel>{data.settings.domains.map(rule => <Panel key={rule.host}><Toggle title={rule.host} detail={rule.allow ? "Allowed exception" : "Blocked with subdomains"} value={rule.enabled} onChange={enabled => void command("domain", { domain: rule.host, allow: rule.allow, enabled })} /><Button title="Remove rule" tone="secondary" onPress={() => void command("domain", { domain: rule.host, remove: true })} /></Panel>)}
  </View>;
}

const socials = ["com.instagram.android", "com.google.android.youtube", "com.facebook.katana", "com.snapchat.android", "com.zhiliaoapp.musically", "com.ss.android.ugc.trill"];
const blankRule = (packageName: string): AppRule => ({ packageName, enabled: true, limitMinutes: 0, startMinute: -1, endMinute: -1, days: [1,2,3,4,5,6,7], feedMode: "off", burst: true });
export function AppsScreen({ socialOnly = false }: { socialOnly?: boolean }) {
  const { snapshot: data, run } = useOffline();
  const [apps, setApps] = useState<InstalledApp[]>([]); const [loaded, setLoaded] = useState(false); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<InstalledApp | null>(null);
  const load = () => void run(async () => { setApps(await offlineProtection.apps()); setLoaded(true); });
  useEffect(() => { let live = true; void offlineProtection.apps().then(items => { if (live) { setApps(items); setLoaded(true); } }).catch(() => { if (live) setLoaded(false); }); return () => { live = false; }; }, []);
  if (!data) return null;
  if (selected) return <RuleEditor app={selected} initial={data.settings.rules.find(rule => rule.packageName === selected.packageName) ?? blankRule(selected.packageName)} close={() => setSelected(null)} />;
  return <View style={ui.stack}><Heading title={socialOnly ? "Less scrolling. More living." : "Your apps, your limits"} subtitle={socialOnly ? "Choose feed restrictions or a whole-app pause." : "Set daily limits, schedules, and apps to pause during Burst."} />{!data.capabilities.accessibility && <Panel><Body>App restrictions need Accessibility access. Usage limits also need Usage Access. Configure both in Protection setup.</Body></Panel>}{socialOnly && <Panel><Body>Feed-only detection is experimental for YouTube and Instagram and may stop working after app updates. Facebook, Snapchat and TikTok currently use the whole-app option. No unsupported version is advertised as reliably covered.</Body></Panel>}<Field label="Find an installed app" value={search} onChange={setSearch} />{!loaded && <Button title="Load installed apps" onPress={load} />}<Panel>{apps.filter(app => (!socialOnly || socials.includes(app.packageName)) && app.label.toLowerCase().includes(search.toLowerCase())).map(app => { const rule = data.settings.rules.find(rule => rule.packageName === app.packageName); return <LinkRow key={app.packageName} title={app.label} detail={rule?.enabled ? `${rule.limitMinutes ? `${rule.limitMinutes} min/day · ` : ""}${rule.feedMode === "whole_app" ? "App paused" : rule.feedMode === "experimental" ? "Experimental feed rule" : "Custom rules"}` : "No active rule"} icon="cellphone" onPress={() => setSelected(app)} />; })}{loaded && apps.filter(app => !socialOnly || socials.includes(app.packageName)).length === 0 && <Body>No matching launchable apps are installed.</Body>}</Panel></View>;
}
function RuleEditor({ app, initial, close }: { app: InstalledApp; initial: AppRule; close: () => void }) {
  const { command } = useOffline();
  const [rule, setRule] = useState(initial); const [limit, setLimit] = useState(initial.limitMinutes ? String(initial.limitMinutes) : "");
  const [start, setStart] = useState(initial.startMinute < 0 ? "" : minuteString(initial.startMinute)); const [end, setEnd] = useState(initial.endMinute < 0 ? "" : minuteString(initial.endMinute));
  const [validation, setValidation] = useState("");
  const save = async () => {
    const startMinute = parseTime(start); const endMinute = parseTime(end); const limitMinutes = limit.trim() ? Number(limit) : 0;
    if (!Number.isInteger(limitMinutes) || limitMinutes < 0 || limitMinutes > 1440 || startMinute === null || endMinute === null || ((startMinute === -1) !== (endMinute === -1)) || (startMinute >= 0 && startMinute === endMinute) || !rule.days.length) { setValidation("Use a whole-number limit and valid HH:MM start/end times. Select at least one day."); return; }
    if (await command("rule", { ...rule, limitMinutes, startMinute, endMinute })) close();
  };
  return <View style={ui.stack}><Heading title={app.label} subtitle="Restrictions apply only while this app is in the foreground." /><Panel><Toggle title="Enable this rule" value={rule.enabled} onChange={enabled => setRule({ ...rule, enabled })} /><Field label="Daily limit in minutes (blank = no limit)" value={limit} onChange={setLimit} numeric /><Field label="Schedule start · HH:MM" value={start} onChange={setStart} placeholder="22:00" /><Field label="Schedule end · HH:MM" value={end} onChange={setEnd} placeholder="07:00" /><Body>Leave both times empty to disable the schedule. Overnight schedules use the selected start day.</Body><View style={ui.wrap}>{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day, i) => <Button key={day} title={day} tone={rule.days.includes(i+1) ? "primary" : "secondary"} onPress={() => setRule({ ...rule, days: rule.days.includes(i+1) ? rule.days.filter(n => n !== i+1) : [...rule.days, i+1] })} />)}</View><Toggle title="Pause this app during Burst" value={rule.burst} onChange={burst => setRule({ ...rule, burst })} /></Panel><Panel><Body strong>Feed / app restriction</Body>{(["off", ...(app.packageName === "com.google.android.youtube" || app.packageName === "com.instagram.android" ? ["experimental"] : []), "whole_app"] as AppRule["feedMode"][]).map(mode => <Button key={mode} title={mode === "off" ? "No feed restriction" : mode === "experimental" ? "Feed only · experimental" : "Pause the whole app"} tone={rule.feedMode === mode ? "primary" : "secondary"} onPress={() => setRule({ ...rule, feedMode: mode })} />)}<Body>The experimental adapter uses visible interface identifiers. If an app update breaks recognition, choose the whole-app restriction.</Body></Panel>{!!validation && <Body>{validation}</Body>}<Button title="Save app rule" onPress={() => void save()} /><Button title="Remove rule" tone="secondary" onPress={() => void command("rule", { packageName: app.packageName, remove: true }).then(ok => { if (ok) close(); })} /><Button title="Back to apps" tone="secondary" onPress={close} /></View>;
}
export function parseTime(value: string): number | null { if (!value.trim()) return -1; if (!/^([01]\d|2[0-3]):[0-5]\d$/.test(value)) return null; const [h,m] = value.split(":").map(Number); return h! * 60 + m!; }
function minuteString(value: number) { return `${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`; }

export function BurstScreen({ open }: { open: (route: string) => void }) {
  const { snapshot: data, command } = useOffline();
  const [minutes, setMinutes] = useState(data?.settings.burstMinutes ? String(data.settings.burstMinutes) : "");
  if (!data) return null;
  return <View style={ui.stack}><Heading title="Make room for a choice" subtitle="Put the phone down. Stand up and walk into another room." /><Panel><Body strong>{data.burstRemainingMs > 0 ? `${Math.ceil(data.burstRemainingMs/60000)} minutes of space remaining` : "Your emergency pause"}</Body><Body>Burst pauses the apps you selected. Its cooldown continues after you mark the urge resisted; settings cannot be weakened early.</Body><Body>{data.settings.rules.filter(rule => rule.enabled && rule.burst).length} apps selected for Burst.</Body>{data.burstRemainingMs > 0 ? <Button title="I resisted this urge" disabled={data.events.some(event => event.id === data.settings.burstId && event.resisted)} onPress={() => void command("resist", { id: data.settings.burstId })} /> : <><Field label="Your cooldown · minutes" value={minutes} onChange={setMinutes} numeric /><Button title="Save duration" tone="secondary" disabled={!minutes} onPress={() => void command("setting", { key: "burstMinutes", value: Number(minutes) })} /><Button title="Activate Burst" icon="lightning-bolt" tone="danger" onPress={() => void command("burst")} /></>}<Button title="Choose Burst apps" tone="secondary" onPress={() => open("apps")} /></Panel><Panel><Body strong>For the next minute</Body><Body>1. Leave the room and take a short walk.</Body><Body>2. Breathe slowly. You only need to choose your next action.</Body></Panel></View>;
}

export function SettingsScreen({ open }: { open: (route: string) => void }) {
  const { snapshot: data, command } = useOffline(); const [strict, setStrict] = useState(""); if (!data) return null;
  return <View style={ui.stack}><Heading title="Your space, your rules" subtitle="Private by default. Everything in this edition stays on your phone." /><Panel><LinkRow title="Protection setup" detail="Access, notifications & battery" icon="shield-check-outline" onPress={() => open("permissions")} /><LinkRow title="Website protection" detail="Private DNS, local VPN & domains" icon="web" onPress={() => open("web")} /><LinkRow title="Apps & schedules" icon="cellphone-lock" onPress={() => open("apps")} /><LinkRow title="Social feeds" icon="play-box-outline" onPress={() => open("social")} /><LinkRow title="Visual filtering" detail="Not included in this offline build" icon="eye-off-outline" onPress={() => open("visual")} /></Panel><Label>RECOVERY & APPEARANCE</Label><Panel><Toggle title="Recovery tracking" value={data.settings.recoveryEnabled} onChange={value => void command("setting", { key: "recoveryEnabled", value })} /><Toggle title="Optional Fap Tracker" detail="Independent of your protection settings." value={data.settings.trackerEnabled} onChange={value => void command("setting", { key: "trackerEnabled", value })} /><View style={ui.wrap}>{(["system", "light", "dark"] as const).map(value => <Button key={value} title={value[0]!.toUpperCase()+value.slice(1)} tone={data.settings.theme === value ? "primary" : "secondary"} onPress={() => void command("setting", { key: "theme", value })} />)}</View></Panel><Label>PROTECTION FRICTION</Label><Panel><Body strong>Lock your settings</Body><Body>A deliberate cooldown prevents changes from weakening protection inside Restrainify. It does not prevent uninstalling or revoking access in Android Settings.</Body>{data.strictRemainingMs > 0 ? <Body>{Math.ceil(data.strictRemainingMs/60000)} minutes remaining. Protection changes are locked.</Body> : <><Field label="Lock duration · minutes" value={strict} onChange={setStrict} numeric placeholder={String(data.settings.strictMinutes || "")} /><Button title="Save lock duration" tone="secondary" disabled={!strict} onPress={() => void command("setting", { key: "strictMinutes", value: Number(strict) })} /><Button title="Lock protection settings" onPress={() => Alert.alert("Lock protection settings?", `Changes that weaken protection will be unavailable for ${data.settings.strictMinutes} minutes.`, [{ text: "Cancel" }, { text: "Lock", onPress: () => void command("strict") }])} disabled={!data.settings.strictMinutes} /></>}</Panel><Panel><LinkRow title="Privacy & coverage" icon="lock-outline" onPress={() => open("privacy")} /><Button title="Reset local data" tone="danger" onPress={() => Alert.alert("Delete your local data?", "Recovery history, rewards, rules and settings will be permanently removed from this device. This cannot be undone.", [{ text: "Cancel", style: "cancel" }, { text: "Delete local data", style: "destructive", onPress: () => void command("reset", { confirmed: true }) }])} /></Panel></View>;
}

export function PrivacyScreen() { return <View style={ui.stack}><Heading title="Your privacy, clearly" subtitle="Offline edition · no account required" /><Panel><Body strong>Stored on this phone</Body><Body>Settings, domains, aggregate usage counters, recovery events and daily rewards are held in a SQLCipher-encrypted Room database. Its random key is wrapped by Android Keystore. Device backups are disabled.</Body><Body strong>What leaves the phone</Body><Body>When you enable the DNS VPN, domain lookup requests go to Cloudflare Families (1.1.1.3). Explicit allowed exceptions use 1.1.1.1. Queries use standard UDP DNS; network operators may observe them. Private DNS provides encrypted transport through Android but cannot apply your local custom rules.</Body><Body strong>What is never collected</Body><Body>No screenshots, typed messages, page contents or full browsing history are stored. This edition has no account sync, analytics, or visual AI analysis.</Body><Body strong>Coverage limits</Body><Body>Accessibility feed matching depends on app versions and UI identifiers. Secure DNS inside other apps, direct IP connections, OEM service shutdowns and permission revocation can reduce coverage. Adult self-control provides friction, not guaranteed uninstall prevention.</Body><Body strong>Deleting records</Body><Body>Reset local data removes the app's product records and configuration after confirmation. It is unavailable during an active protection cooldown.</Body></Panel></View>; }
