import { useState } from "react";
import { Alert, Text, View } from "react-native";
import { useOffline } from "../../app/providers/OfflineProvider";
import { Body, Button, Field, Heading, Icon, Label, LinkRow, Panel, Toggle, ui, duration } from "../../components/OfflineUI";
import type { LocalEvent } from "../../native/OfflineProtection";
import { OnboardingAuthCard } from "../auth";

export function ProgressScreen({ open }: { open: (route: string) => void }) {
  const { snapshot: data, palette } = useOffline(); if (!data) return null;
  const relapseDays = new Set(data.events.filter(event => event.kind === "relapse").map(event => event.day));
  return <View style={ui.stack}><Heading title="Progress stays with you" subtitle="A difficult day does not erase the days that came before it." /><Panel><View style={ui.row}><Icon name="chart-timeline-variant" /><Body strong>Your recovery</Body></View><Text style={{ fontSize: 52, fontWeight: "700", letterSpacing: -2, color: palette.textPrimary }}>{data.recovery.current}<Text style={{ fontSize: 16 }}> days</Text></Text><Body>{data.recovery.longest} day longest streak · {data.recovery.cleanDays} porn-free days in your last 30</Body><Body>Tracking since {data.settings.recoveryStart}</Body></Panel><Label>THE LAST 30 DAYS</Label><Panel><View style={ui.wrap}>{Array.from({ length: 30 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - (29-index)); const day = localDay(date); const started = day >= data.settings.recoveryStart; const relapse = relapseDays.has(day); return <View key={day} accessibilityLabel={`${day}: ${!started ? "before tracking" : relapse ? "relapse recorded" : "no relapse recorded"}`} style={{ width: "12%", height: 40, borderRadius: 10, backgroundColor: !started ? palette.surfaceMuted : relapse ? palette.dangerSurface : palette.successSurface, alignItems: "center", justifyContent: "center" }}><Text style={{ color: !started ? palette.textMuted : relapse ? palette.danger : palette.success, fontWeight: "600" }}>{date.getDate()}</Text></View>; })}</View><Body>Green: no relapse recorded · Red: relapse recorded · Gray: before tracking</Body><Button title="Open recovery journal" tone="secondary" onPress={() => open("journal")} /></Panel><Label>TIME & ATTENTION</Label><Panel><Body strong>{data.capabilities.usage ? duration(data.usage.todayMs) : "Usage Access needed"}</Body><Body>Total foreground time today. Data is read from Android UsageStats and depends on the history your device retains.</Body>{data.usage.apps.slice(0,10).map(app => <View key={app.packageName} style={ui.row}><View style={{ flex: 1 }}><Body>{app.label}</Body></View><Body strong>{duration(app.ms)}</Body></View>)}<Button title="Set an app limit" tone="secondary" onPress={() => open("apps")} /></Panel></View>;
}
export function localDay(date: Date) { return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`; }
function localDateTime() { const date = new Date(); return `${localDay(date)}T${String(date.getHours()).padStart(2,"0")}:${String(date.getMinutes()).padStart(2,"0")}`; }
export function JournalScreen({ tracker = false }: { tracker?: boolean }) {
  const { snapshot: data, command } = useOffline();
  const [kind, setKind] = useState<"urge" | "relapse">("urge"); const [note, setNote] = useState(""); const [when, setWhen] = useState(localDateTime); const [resisted, setResisted] = useState(false); const [visible, setVisible] = useState(30); const [validation, setValidation] = useState("");
  if (!data) return null;
  const enabled = tracker ? data.settings.trackerEnabled : data.settings.recoveryEnabled;
  const events = data.events.filter(event => tracker ? event.kind === "tracker" : event.kind !== "tracker");
  const save = async () => {
    const timestamp = new Date(when).getTime();
    if (!Number.isFinite(timestamp) || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(when) || timestamp > Date.now()) { setValidation("Enter a valid past date and time: YYYY-MM-DDTHH:MM."); return; }
    const submit = async () => { if (await command("event", { kind: tracker ? "tracker" : kind, timestamp, note, resisted })) { setNote(""); setWhen(localDateTime()); setValidation(""); } };
    if (!tracker && kind === "relapse") Alert.alert("Record a relapse?", "Your current streak will be recalculated. Your history and longest streak will stay.", [{ text: "Cancel" }, { text: "Record", onPress: () => void submit() }]); else await submit();
  };
  return <View style={ui.stack}><Heading title={tracker ? "Private tracker" : "A moment to reflect"} subtitle={tracker ? "Optional, personal, and independent of protection." : "Notice what happened. Decide what comes next."} /><Panel>{!enabled ? <><Body>This tracker is off. Existing history is preserved, and new events cannot be created.</Body><Button title="Enable tracking" onPress={() => void command("setting", { key: tracker ? "trackerEnabled" : "recoveryEnabled", value: true })} /></> : <>{!tracker && <View style={ui.wrap}>{(["urge", "relapse"] as const).map(value => <Button key={value} title={value === "urge" ? "An urge" : "A relapse"} tone={kind === value ? "primary" : "secondary"} onPress={() => setKind(value)} />)}</View>}<Field label="Date & time · local" value={when} onChange={setWhen} placeholder="2026-09-10T18:30" /><Field label="What was happening? (optional)" value={note} onChange={setNote} multiline placeholder="A short note, just for you." />{!tracker && kind === "urge" && <Toggle title="I resisted this urge" value={resisted} onChange={setResisted} />}{!!validation && <Body>{validation}</Body>}<Button title={tracker ? "Record private event" : "Save journal entry"} icon="check" onPress={() => void save()} /></>}</Panel><Label>YOUR HISTORY · RECENT {events.length} ENTRIES</Label>{events.length === 0 ? <Panel><Body>No entries yet. Your next step can be a small one.</Body></Panel> : events.slice(0,visible).map(event => <EventRow key={event.id} event={event} />)}{events.length > visible && <Button title="Show more entries" tone="secondary" onPress={() => setVisible(value => value+30)} />}</View>;
}
function EventRow({ event }: { event: LocalEvent }) { const { command } = useOffline(); return <Panel><Body strong>{event.kind === "burst" ? "Burst intervention" : event.kind === "tracker" ? "Private event" : event.kind === "urge" ? "An urge" : "Relapse recorded"}{event.resisted ? " · resisted" : ""}</Body><Body>{new Date(event.timestamp).toLocaleString()}</Body>{!!event.note && <Body>{event.note}</Body>}{(event.kind === "urge" || event.kind === "burst") && !event.resisted && <Button title="Mark resisted" tone="secondary" onPress={() => void command("resist", { id: event.id })} />}</Panel>; }
export function ToolsScreen({ open }: { open: (route: string) => void }) { return <View style={ui.stack}><Heading title="A little more control" subtitle="Practical tools for the moments that matter." /><Panel><LinkRow title="Burst" detail="Pause selected apps with one action" icon="lightning-bolt-outline" onPress={() => open("burst")} /><LinkRow title="Social feed restrictions" detail="Reels, Shorts & whole-app pauses" icon="play-box-outline" onPress={() => open("social")} /><LinkRow title="App limits & schedules" detail="Make boundaries that fit your day" icon="timer-outline" onPress={() => open("apps")} /><LinkRow title="Website protection" detail="DNS & your personal domain rules" icon="web" onPress={() => open("web")} /><LinkRow title="Optional private tracker" detail="Your records stay on this device" icon="notebook-outline" onPress={() => open("tracker")} /></Panel></View>; }
export function Onboarding({ finish }: { finish: () => void }) {
  const { snapshot: data, command } = useOffline(); const [step, setStep] = useState(0); const [baseline, setBaseline] = useState(data?.settings.recoveryStart ?? localDay(new Date()));
  if (!data) return null;
  return <View style={ui.stack}><Label>RESTRAINIFY / {step+1} OF 4</Label>{step === 0 ? <><Heading title="More room for real life." subtitle="Build boundaries around the apps and websites that pull you away." /><Panel><Body>This offline edition keeps recovery history encrypted on your phone. No account, cloud sync or visual AI analysis is used.</Body><Body>You choose which Android permissions to enable. Nothing is activated before you see an explanation and agree.</Body></Panel><Button title="Let's get started" onPress={() => setStep(1)} /></> : step === 1 ? <><Heading title="Start where you are." subtitle="Choose a recovery baseline. A setback will never erase your history." /><Panel><Field label="Recovery start · YYYY-MM-DD" value={baseline} onChange={setBaseline} /><Toggle title="Track recovery" value={data.settings.recoveryEnabled} onChange={value => void command("setting", { key: "recoveryEnabled", value })} /><Toggle title="Enable the optional private tracker" value={data.settings.trackerEnabled} onChange={value => void command("setting", { key: "trackerEnabled", value })} /></Panel><Button title="Save & continue" onPress={() => void command("setting", { key: "recoveryStart", value: baseline }).then(ok => { if (ok) setStep(2); })} /></> : step === 2 ? <OnboardingAuthCard onContinue={() => setStep(3)} onSkip={() => setStep(3)} /> : <><Heading title="Your next step is yours." subtitle="Your home is ready. Connect protection whenever you're ready." /><Panel><Body>Website protection uses a local DNS VPN or Android Private DNS. App limits and feed restrictions need Accessibility; usage tracking needs Usage Access.</Body><Body>The app will show a disconnected or incomplete status until those capabilities are actually available. Visual filtering is not part of this build.</Body></Panel><Button title="Open my home" onPress={() => void command("onboard").then(ok => { if (ok) finish(); })} /></>}{step > 0 && <Button title="Back" tone="secondary" onPress={() => setStep(value => value-1)} />}</View>;
}
